package com.university.alumni.user.service;

import com.university.alumni.auth.service.EmailService;
import com.university.alumni.user.dto.BugReportRequest;
import com.university.alumni.user.entity.User;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class SupportService {

    private final EmailService emailService;

    private static final String ADITI_EMAIL = "pandeyaditi0307@gmail.com";
    private static final String YASH_EMAIL = "yashdubey262@gmail.com";

    public void sendBugReport(BugReportRequest request, User sender) {
        String subject = "BUG REPORT: " + request.title();
        String body = String.format(
            "New Bug Report from: %s %s (%s)\n\n" +
            "Title: %s\n\n" +
            "Information:\n%s\n\n" +
            "--- Generated by Alumni Portal Support System ---",
            sender.getFirstName(), sender.getLastName(), sender.getEmail(),
            request.title(),
            request.information()
        );

        List<String> recipients = request.recipients();
        if (recipients.contains("Aditi Pandey")) {
            emailService.sendEmail(ADITI_EMAIL, subject, body);
        }
        if (recipients.contains("Yash Dwivedi")) {
            emailService.sendEmail(YASH_EMAIL, subject, body);
        }

        log.info("Bug report '{}' sent to recipients: {}", request.title(), recipients);
    }
}
